### ISSUE TITLE
No submitting

### ISSUE THREAD

**Issue by jagajaga** [aszlig/LastWatch#2]
Hello!
Just installed on nixos.
Entered login and pass, directory. All files are watched. But no submitting is going.
Please change smth, or help me :)

**Comment by aszlig** [comment]
Ah, could it be that your audio player is using mmap() for reading the audio files? Which player are you using?

**Comment by jagajaga** [comment]
moc (music on console).

2013/12/19 aszlig notifications@github.com

**Comment by aszlig** [comment]
Okay, this one prebuffers the file in memory and closes the file as soon as the file is fully in buffer. Unfortunately, this means, that you either have to disable buffering or (preferably) we find a better method on detecting things like this.

So, maybe you have an idea on how to solve this properly? Because inotify only gives us operations on the files, not what the process is actually doing with the file. We might need some introspection on the process itself, but possibly without using ptrace() or similar scary things™.

At the moment, lastwatch only looks at the time span between when a file was opened and when it got closed.

**Comment by jagajaga** [comment]
Well, we can do very easy solution - submit all the files, which were opened. Like lastfmsubmitd does.
I saw that you're checking time.
